### ISSUE TITLE
Magick++ Package Dependency

### ISSUE THREAD

**Issue by abdulbaasitt** [ahmedadamji/PathPlanning#2]
Hi @ahmedadamji 

I noticed a dependency on the `Magick++` package while trying to build this project. 

`fatal error: Magick++.h: No such file or directory
 #include <Magick++.h>
`

Thankfully, the `Magick++` package can be installed from the apt repository for ubuntu using 

`sudo apt-get install libmagick++-dev
`

I have updated the readMe and created a PR to close this issue.

**Comment by abdulbaasitt** [comment]
Fixed in a PR

**Comment by ahmedadamji** [comment]
Hello @abdulbaasitt.
Thank you for bringing this issue to my attention and for the proactive approach in creating a PR to fix it.
I will review your Pull Request shortly to ensure that it aligns with the project.
The changes will be tested to ensure that the dependency issue is fully resolved.
Once confirmed, I will merge your PR and close this issue.
